# Generated by Django 5.0.1 on 2024-01-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
